### ISSUE TITLE
Change the text on button

### ISSUE THREAD

**Issue by harshita795** [harshita795/Counter-App#2]
**To Reproduce**
*Steps to reproduce the behavior:*

1.  First **fork** the repo.
2. Then copy the **code** link from the forked repo.
3. Clone the repo using the command:  ```git clone -URL of code-```
4. Go to the **Index.html** file and change the text in the button tag.
5. The text is **Add**.
6. Modify it to the text **Upper**.

**Screenshots**
![Screenshot (41)](https://github.com/harshita795/Counter-App/assets/73014908/84c0baf0-9ce3-4154-b8da-171cf7822ec5)

**Thanks for your contribution!!**

**Comment by Saurabh-827** [comment]
Attempting #2
